# Generated by Django 4.2 on 2023-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_brand_image/default_brand_image.jpg', upload_to='product_images/', verbose_name='Image'),
        ),
    ]
