# Generated by Django 4.2 on 2023-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default_brand_image/default_brand_image.jpg', upload_to='product_images/', verbose_name='Image'),
        ),
    ]
