# Generated by Django 4.2 on 2023-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
                ('basket_history', models.JSONField(default=dict, verbose_name='Basket History')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'On Way'), (3, 'Delivered')], default=0, verbose_name='Status')),
            ],
        ),
    ]
